some modifications

diff --git a/.github/workflows/clean_tree.yaml b/.github/workflows/clean_tree.yaml
--- a/.github/workflows/clean_tree.yaml
+++ b/.github/workflows/clean_tree.yaml
@@ -6,19 +6,22 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
-      - name: Check file existence
-        id: check_files
-        uses: andstor/file-existence-action@v1
-        with:
-          files: "package-lock.json"     
-      - name: Exit When File exists
-        if: steps.check_files.outputs.files_exists == 'true'
-        run: exit 1    
       - uses: actions/setup-node@v3
         with:
           node-version: 18     
       - name: Install yarn
         run: npm install -g yarn     
+      - name: make sure package.lock does not exist
+        run: rm -f package-lock.json
+      - name: Check Tree if package-lock.json file was existing and removed
+        run: |
+          if [[ -n $(git status -s) ]]; then
+            echo "ERROR: tree is dirty after removing package-lock.json file"
+            git status
+            exit 1
+          else
+            echo "Working tree is clean."
+          fi
       - name: Install dependencies
         run: yarn
       - name: Check Tree after yarn
