chore: update GitHub Actions to use latest versions of actions and Node.js

diff --git a/.github/workflows/validate.yaml b/.github/workflows/validate.yaml
--- a/.github/workflows/validate.yaml
+++ b/.github/workflows/validate.yaml
@@ -14,28 +14,28 @@ jobs:
   local-tests:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v3
-      - uses: actions/setup-node@v3
+      - uses: actions/checkout@v4
+      - uses: actions/setup-node@v4
         with:
-          node-version: 18
+          node-version: 20
       - name: make sure no yarn.json is added
         run: |
-            if [ -f yarn.json ]; then
-                echo "::error file=yarn.json::yarn.json is being added"
-                exit 1
-            fi
+          if [ -f yarn.json ]; then
+              echo "::error file=yarn.json::yarn.json is being added"
+              exit 1
+          fi
       - name: make sure no package-lock.json is removed
         run: |
-            if [ ! -f package-lock.json ]; then
-                echo "::error file=package-lock.json::package-lock.json is being removed"
-                exit 1
-            fi
+          if [ ! -f package-lock.json ]; then
+              echo "::error file=package-lock.json::package-lock.json is being removed"
+              exit 1
+          fi
       - name: make sure package-lock.json is updated
         run: |
-            if ! npm ci; then
-                echo "::error file=package-lock.json::package-lock.json is not updated"
-                exit 1
-            fi
+          if ! npm ci; then
+              echo "::error file=package-lock.json::package-lock.json is not updated"
+              exit 1
+          fi
       - name: lint
         run: npm run lint
       - name: madge
@@ -45,7 +45,7 @@ jobs:
   build:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v3
+      - uses: actions/checkout@v4
       - name: Get Commit Hash and generate Version File
         run: echo "$(git rev-parse --short HEAD)" >> public/hash.txt
       - name: Set up Docker Buildx
@@ -62,7 +62,7 @@ jobs:
           name: docker-image
           path: /tmp/docker-image.tar
   test:
-    runs-on: ubuntu-22.04
+    runs-on: ubuntu-latest
     needs: build
     env:
       APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
@@ -78,12 +78,12 @@ jobs:
         run: docker load -i /tmp/docker-image.tar
       - name: Run application
         run: docker run -d -p 3000:80 ${{ env.DOCKER_APP_IMAGE_NAME }}:${{ env.DOCKER_APP_IMAGE_TAG }}
-      - uses: actions/checkout@v3
+      - uses: actions/checkout@v4
         with:
           ref: ${{ github.event.pull_request.head.sha }}
-      - uses: actions/setup-node@v3
+      - uses: actions/setup-node@v4
         with:
-          node-version: 18
+          node-version: 20
       - name: Validate hash.txt file
         run: |
           response=$(curl -s -w "%{http_code}" -o /tmp/hash.txt http://localhost:3000/hash.txt)
@@ -131,7 +131,6 @@ jobs:
           path: logs
           if-no-files-found: warn
 
-
   publish-test-results:
     runs-on: ubuntu-latest
     needs: test
@@ -168,17 +167,17 @@ jobs:
   build-outside-docker:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v3
-      - uses: actions/setup-node@v3
+      - uses: actions/checkout@v4
+      - uses: actions/setup-node@v4
         with:
-          node-version: 18
+          node-version: 20
       - name: Run install
         run: npm ci
       - name: build
         run: npm run build
       - name: build storybook
         run: npm run build-storybook
-      
+
   all-passed:
     runs-on: ubuntu-latest
     needs: [local-tests, test]
